services:
  postgres:
    build:
      context: ./image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: playground
    ports:
      - "54320:5432"
